config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:show]
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :dashboard

  # Defines the root path route ("/")
  root "dashboards#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events

  validates :identifier, presence: true
  validates :name, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  enum status: { active: "active", removed: "removed" }

  belongs_to :category

  validates :name, presence: true
  validates :started_at, presence: true
  validates :finished_at, presence: true
  validates :name, length: { minimum: 3, maximum: 100, allow_blank: true }
  validate :validate_if_starts_in_future, on: :create
  validate :validate_if_finished_greater_than_started

  scope :with_category, -> { includes(:category) }
  scope :today, -> { where(started_at: Date.current.beginning_of_day..Date.current.end_of_day) }
  scope :in_period, ->(period_start, period_end) { where("started_at >= ? AND started_at <= ?", period_start, period_end) }

  has_one_attached :file
  has_rich_text :description

  private

  def validate_if_finished_greater_than_started
    return unless started_at
    return unless finished_at
    return if finished_at > started_at

    errors.add(:finished_at, :invalid)
  end

  def validate_if_starts_in_future
    return unless started_at
    return if started_at >= Time.current

    errors.add(:started_at, :invalid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.order(:name)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      redirect_to categories_path, notice: "Categoria criada com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update category_params
      redirect_to categories_path, notice: "Categoria atualizada com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Categoria removida com sucesso."
  end

  private

  def category_params
    params.require(:category).permit(:identifier, :name)
  end

  def load_category
    @category = Category.find params[:id]
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @events = Event.order(:started_at).as_json(only: [:id, :name, :started_at, :finished_at])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event)
          .permit(:name, :description, :started_at, :finished_at, :category_id, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_category.html.erb
<div class="card">
  <div class="card-body">
    <h2><%= category.name %></h2>
  </div>
  <div class="card-footer d-flex justify-content-between">
    <%= link_to "Editar", edit_category_path(category), class: "btn btn-secondary" %>
    <%= button_to "Remover", category_path(category), method: :delete, class: "btn btn-danger", data: { turbo_confirm: "Você tem certeza?" } %>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="card">
  <%= simple_form_for @category do |form| %>
    <div class="card-body">
      <%= form.input :identifier %>
      <%= form.input :name %>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <%= link_to "Voltar", categories_path, class: "btn btn-secondary" %>
      <%= form.button :button, class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<div class="w-100 d-flex">
  <h1 class="flex-grow-1">Categorias</h1>
  <div>
    <%= link_to "Nova Categoria", new_category_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="d-flex flex-column gap-4">
  <%= render @categories %>
</div>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/dashboards/show.html.erb
<div data-controller="calendar" data-calendar-events-value="<%= @events.to_json %>">
  <div data-calendar-target="container"></div>
</div>

app/views/events/_event.html.erb
<div class="card" id="<%= dom_id event %>">
  <div class="card-body">
    <p>
      <strong>Name:</strong>
      <%= event.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= event.description %>
    </p>

    <p>
      <strong>Started at:</strong>
      <%= l event.started_at %>
    </p>

    <p>
      <strong>Finished at:</strong>
      <%= l event.finished_at %>
    </p>

    <% if event.file.attached? %>
      <%= link_to "Baixar Anexo", event.file, class: "btn btn-secondary", target: :blank %>
    <% end %>
  </div>
  <div class="card-footer d-flex justify-content-between">
    <%= link_to "Editar", edit_event_path(event), class: "btn btn-secondary" %>
    <%= button_to "Remover", event_path(event), method: :delete, class: "btn btn-danger", data: { turbo_confirm: "Você tem certeza?" } %>
  </div>
</div>

app/views/events/_form.html.erb
<div class="card">
  <%= simple_form_for event do |form| %>
    <div class="card-body">
      <%= form.input :name %>

      <%= form.input :description do %>
        <%= form.rich_text_area :description %>
      <% end %>

      <%= form.association :category %>
      <div class="row">
        <div class="col-12 col-md-6">
          <%= form.input :started_at, html5: true %>
        </div>
        <div class="col-12 col-md-6">
          <%= form.input :finished_at, html5: true %>
        </div>
      </div>
      <%= form.input :file %>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <%= link_to "Voltar", events_path, class: "btn btn-secondary" %>
      <%= form.button :button, class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t "views.events.form.edit" %></h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<div class="w-100 d-flex">
  <h1 class="flex-grow-1">Eventos</h1>
  <div>
    <%= link_to "Novo Evento", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="d-flex flex-column gap-4">
  <%= render @events %>
</div>

app/views/events/new.html.erb
<h1><%= t "views.events.form.new" %></h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<%= render @event %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyAgenda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container my-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      EasyAgenda
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Eventos", events_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categorias", categories_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>